# Generated by Django 3.2.9 on 2023-02-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tik_tak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер телефона'),
        ),
    ]
